var firstname ='Rizma';
var lastname = 'Karim';
var age = 30 ;
var dateOfBirth = 02/28/1990 ;
var address = '5471 arcadia road' ;
console.log( 'firstname : ', firstname);
console.log( 'lastname : ', lastname);
console.log( 'age : ', age);
console.log( 'dateOfbirth : ', dateOfBirth);
console.log( 'address : ',  address);